Repository sprint-9-3/albaform, pull requests merged in 2024-11, with the labels that each got.

#61 Feat(60): PR template 추가
  pull_request_template.md
Labels: 🧑‍💻 Feat

#75 Feat: SolidButton 구현
  src/components/button/SolidButton.tsx
  tailwind.config.ts
Labels: 🧑‍💻 Feat

#77 Feat: Applicationcard 구현
  next.config.ts
  src/components/card/AlbarCard.tsx
  src/components/card/ApplicantCard.tsx
  src/types/alba.ts
  src/utils/getCurrentTime.ts
  src/utils/isPast.ts
Labels: 🧑‍💻 Feat

#78 Feat: FloatingButton 구현
  src/components/button/FloatingButton.tsx
  tailwind.config.ts
Labels: 🧑‍💻 Feat

#79 Feature: RadioButton 구현
  src/components/button/RadioButton.tsx
Labels: 🧑‍💻 Feat

#76 Feat: 회원가입 및 로그인 구현
  bun.lockb
  package.json
  src/app/(auth)/components/AuthNav.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/signin/[userType]/page.tsx
  src/app/(auth)/signin/actions/signinActions.ts
  src/app/(auth)/signin/components/SigninContents.tsx
  src/app/(auth)/signin/components/SigninTitle.tsx
  src/app/(auth)/signup/[userType]/page.tsx
  src/app/(auth)/signup/actions/profileImgActions.ts
  src/app/(auth)/signup/actions/signupActions.ts
  src/app/(auth)/signup/components/ProfileImg.tsx
  src/app/(auth)/signup/components/SignupContents.tsx
  src/app/(auth)/signup/components/SignupSecondContents.tsx
  src/app/(auth)/signup/components/SignupTitle.tsx
  src/app/(auth)/signup/components/StepTwoInput.tsx
  src/app/(home)/page.tsx
  src/app/layout.tsx
  src/atoms/signupAtomStore.ts
  src/atoms/tokenAtomStore.ts
  src/components/errorText/ErrorText.tsx
  src/components/input/FormInput.tsx
  src/hooks/useToken.tsx
  src/lib/instance.ts
  src/middleware.ts
  src/schema/signin/signinSchema.ts
  src/schema/signup/signupSchema.ts
  src/styles/globals.css
  src/utils/DynamicTailwind.ts
Labels: 🧑‍💻 Feat

#82 Feat: Employerinfo 컴포넌트 UI 구현
  src/components/EmployerInfo.tsx
  src/utils/getDday.ts
  tailwind.config.ts
Labels: 🧑‍💻 Feat

#83 feat: "내 지원 내역" 모달 UI 구현
  bun.lockb
  src/app/modaltest/page.tsx
  src/components/modal/modalContent/GetMyApplicationModal.tsx
  src/components/modal/modalManager/ModalManager.tsx
  src/schema/modal/GetMyApplicationSchema.ts
  src/types/modal.tsx
Labels: 🧑‍💻 Feat

#90 Feat: RecruitInfoCard 구현
  src/app/page.tsx
  src/components/RecruitInfoCard.tsx
Labels: 🧑‍💻 Feat

#95 feat: "내 정보 수정" 모달 UI 구현
  public/icons/X.svg
  public/images/close-albaform.svg
  public/images/delete-albaform.svg
  public/images/patch-albaform.svg
  src/app/modaltest/page.tsx
  src/components/modal/modalContainer/ModalContainer.tsx
  src/components/modal/modalContent/ChangeMyInfoModal.tsx
  src/components/modal/modalContent/ClosedAlbaformModal.tsx
  src/components/modal/modalContent/DeleteAlbaformModal.tsx
  src/components/modal/modalContent/GetMyApplicationModal.tsx
  src/components/modal/modalContent/PatchAlbaformModal.tsx
  src/components/modal/modalManager/ModalManager.tsx
  src/hooks/useModal.ts
  src/schema/modal/changeMyInfoSchema.ts
  src/schema/modal/getMyApplicationSchema.ts
  src/styles/globals.css
  src/types/modal.ts
  tsconfig.json
Labels: 🧑‍💻 Feat

#89 Feat: CheckBoxButton 구현
  src/components/button/CheckBoxButton.tsx
Labels: 🧑‍💻 Feat

#98 Feat: 드롭다운 구현
  src/app/(auth)/components/AuthNav.tsx
  src/app/(auth)/signin/components/SigninContents.tsx
  src/app/(auth)/signup/components/SignupContents.tsx
  src/app/(auth)/signup/components/SignupSecondContents.tsx
  src/atoms/dropdownAtomStore.ts
  src/components/dropdown/ApplicationDropdown.tsx
  src/components/dropdown/DropdownMenu.tsx
  src/components/errorText/ErrorText.tsx
  src/components/input/FormInput.tsx
  src/hooks/useToken.ts
  src/utils/dynamicTailwinds.ts
Labels: 🧑‍💻 Feat

#101 Feat: PostCard ui컴포넌트 구현
  next.config.ts
  public/icon/comment-hover.svg
  public/icon/heart-hover.svg
  src/app/test/page.tsx
  src/components/CommentAndLikeCount.tsx
  src/components/UserInfoInCard.tsx
  src/components/card/PostCard.tsx
  src/types/alba.ts
  src/utils/formatDate.ts
Labels: 🧑‍💻 Feat

#102 Feat: CommentCard ui컴포넌트 구현
  public/icon/document-empty-md.svg
  public/icon/document-hover.svg
  src/app/test/page.tsx
  src/components/card/.next/trace
  src/components/card/CommentCard.tsx
  src/components/card/RecruitInfoCard.tsx
Labels: 🧑‍💻 Feat

#103 Feat: CommentItem ui컴포넌트 구현
  src/components/card/AlbarPreview.tsx
  src/components/card/ApplicantStats.tsx
  src/components/card/ApplicationInfo.tsx
  src/components/card/CommentItem.tsx
  src/components/card/DetailRequirements.tsx
  src/components/card/EmployerInfo.tsx
  src/components/card/SimpleRequirements.tsx
Labels: 🧑‍💻 Feat

#109 Feat:"사장님 정보 관리" 모달 UI 구현
  src/app/layout.tsx
  src/app/modaltest/page.tsx
  src/components/modal/modalContainer/ModalContainer.tsx
  src/components/modal/modalContent/ChangeCEOInfoModal.tsx
  src/components/modal/modalContent/ChangeMyInfoModal.tsx
  src/components/modal/modalContent/ClosedAlbaformModal.tsx
  src/components/modal/modalContent/DeleteAlbaformModal.tsx
  src/components/modal/modalContent/GetMyApplicationModal.tsx
  src/components/modal/modalContent/PatchAlbaformModal.tsx
  src/components/modal/modalContent/SelectProgressModal.tsx
  src/components/modal/modalManager/ModalManager.tsx
  src/schema/modal/changeCEOInfoSchema.ts
  src/styles/globals.css
  src/types/modal.ts
Labels: 🧑‍💻 Feat

#110 Feat: 수정 및 삭제 드롭다운 추가
  src/atoms/dropdownAtomStore.ts
  src/atoms/tokenAtom.ts
  src/components/dropdown/DropdownMenu.tsx
  src/components/dropdown/EditDeleteDropdown.tsx
  src/hooks/useToken.ts
Labels: 🧑‍💻 Feat

#104 Feat: 공개여부 드롭다운 추가
  src/atoms/dropdownAtomStore.ts
  src/components/dropdown/DropdownMenu.tsx
  src/components/dropdown/EditDeleteDropdown.tsx
  src/components/dropdown/PublicDropdown.tsx
Labels: 🧑‍💻 Feat

#107 Feat: 채용상태 드롭다운 추가
  src/atoms/dropdownAtomStore.ts
  src/components/dropdown/DropdownMenu.tsx
  src/components/dropdown/RecruitDropdown.tsx
Labels: 🧑‍💻 Feat

#108 Feat: ImageInput 구현
  public/icon/upload-lg.svg
  public/icon/upload-md.svg
  src/components/button/CancelButton.tsx
  src/components/button/DeleteButton.tsx
  src/components/button/ImageInput.tsx
  src/components/button/RoundedButton.tsx
Labels: 🧑‍💻 Feat

#111 Style: dropdownMenu 최신화에 따라 적용할 스타일코드 수정
  src/components/dropdown/ApplicationDropdown.tsx
Labels: 🎨 Style

#112 Chore: 회원가입 및 로그인 비밀번호 스키마 수정
  src/schema/signin/signinSchema.ts
  src/schema/signup/signupSchema.ts
Labels: 🔧 Chore

#114 Feat: 게시글 정렬 드롭다운 추가
  src/atoms/dropdownAtomStore.ts
  src/components/dropdown/DropdownMenu.tsx
  src/components/dropdown/EditDeleteDropdown.tsx
  src/components/dropdown/OrderByDropdown.tsx
  src/components/dropdown/PublicDropdown.tsx
  src/components/dropdown/RecruitDropdown.tsx
Labels: 🧑‍💻 Feat

#113 Feat: Toast UI 구현
  public/icon/user-lg.svg
  public/icon/user-md.svg
  src/app/layout.tsx
  src/atoms/toastAtomStore.ts
  src/components/toast/ToastContainer.tsx
  src/components/toast/ToastItem.tsx
  src/hooks/useToast.ts
  src/styles/globals.css
  src/types/toast.ts
Labels: 🧑‍💻 Feat

#118 Chore: SolidButton style 추가
  src/components/button/SolidButton.tsx
Labels: 🔧 Chore
