Repository sprint-9-3/albaform, pull requests merged in 2024-12, with the labels that each got.

#135 Feat: DatePickerCalendar 컴포넌트 구현
  bun.lockb
  package.json
  public/icon/arrow-fill-bottom.svg
  public/icon/arrow-fill-top.svg
  public/icon/calendar-md.svg
  src/atoms/calendarAtom.ts
  src/components/datepicker/Calendar.tsx
  src/components/datepicker/DatepickerCalendar.tsx
  src/components/datepicker/RangePicker.tsx
  src/styles/customCalendar.css
  src/styles/globals.css
  src/utils/selectRequirementsByLabel.ts
Labels: 🧑‍💻 Feat

#131 Feat: 알바폼 생성 시 단계별 드롭다운 추가
  public/icon/albaform-dropdown-off.svg
  public/icon/albaform-dropdown-on.svg
  src/atoms/dropdownAtomStore.ts
  src/components/dropdown/AlbaformCreateDropdown.tsx
Labels: 🧑‍💻 Feat

#130 Style: Toast 생성 순서 변경
  src/components/toast/ToastContainer.tsx
  src/components/toast/ToastItem.tsx
Labels: 🎨 Style

#134 Chore: 회원가입 및 로그인 토스트 적용 및 에러메세지 한글화
  src/app/(auth)/signin/actions/signinActions.ts
  src/app/(auth)/signin/components/SigninContents.tsx
  src/app/(auth)/signup/actions/signupActions.ts
  src/app/(auth)/signup/components/SignupContents.tsx
  src/schema/signup/signupSchema.ts
Labels: 🔧 Chore

#137 Refactor: 컴포넌트만 리턴하면 label도 같이 보이도록 수정함
  src/app/test/page.tsx
  src/components/picker/Calendar.tsx
  src/components/picker/DatepickerCalendar.tsx
  src/components/picker/RangePicker.tsx
  src/components/picker/RequirementPicker.tsx
Labels: ⚒️ Refactor

#139 Feat: Timepicker 컴포넌트 UI 구현
  public/icon/clock-blank.svg
  src/app/test/page.tsx
  src/components/picker/PickableList.tsx
  src/components/picker/TimePicker.tsx
  src/utils/selectRequirementsByLabel.ts
Labels: 🧑‍💻 Feat

#140 Feat: WeekPicker 컴포넌트 UI 구현
  src/app/test/page.tsx
  src/components/picker/WeekPicker.tsx
Labels: 🧑‍💻 Feat

#161 Style : tailwind 수정
  src/components/card/DetailRequirements.tsx
Labels: 🎨 Style

#162 Style: tailwind 수정, 모바일 반응형 구현
  src/app/test/page.tsx
  src/components/card/EmployerInfo.tsx
Labels: 🎨 Style

#155 Feat: HourlywageInput 컴포넌트 UI 구현
  src/components/card/.next/trace
  src/components/input/HourlyWageInput.tsx
  src/styles/globals.css
Labels: 🧑‍💻 Feat

#158 Feat: 알바토크 페이지 구현
  public/icon/writing-fill.svg
  src/app/albatalk/api/getArticles.ts
  src/app/albatalk/components/AlbatalkList.tsx
  src/app/albatalk/components/AlbatalkSmartSearch.tsx
  src/app/albatalk/layout.tsx
  src/app/albatalk/page.tsx
  src/components/button/AddtalkButton.tsx
  src/components/card/PostCard.tsx
  src/components/input/SearchInput.tsx
  src/types/post.ts
Labels: 🧑‍💻 Feat

#159 Refactor: 쿠키관리 서버컴포넌트로 이관
  src/app/(auth)/signin/actions/signinActions.ts
  src/app/(auth)/signin/components/SigninContents.tsx
  src/app/(auth)/signup/actions/profileImgActions.ts
  src/app/(auth)/signup/actions/signupActions.ts
  src/app/(auth)/signup/components/ProfileImg.tsx
  src/app/(auth)/signup/components/SignupContents.tsx
  src/atoms/tokenAtom.ts
  src/hooks/useToken.ts
  src/lib/cookie.ts
  src/lib/instance.ts
  src/middleware.ts
Labels: ⚒️ Refactor

#166 Feat: StoreLocation 컴포넌트 구현 -> 알바폼상세페이지 근무지역
  bun.lockb
  global.d.ts
  package.json
  src/app/test/page.tsx
  src/components/button/CopyButton.tsx
  src/components/card/StoreLocation.tsx
  src/components/map/KakaoMap.tsx
  src/components/map/useKakaoLoader.ts
Labels: 🧑‍💻 Feat

#160 Feat: 알바 목록 페이지 구현
  next.config.ts
  public/icon/empty-lg.svg
  public/icon/empty-md.svg
  public/icon/private-lg.svg
  public/icon/private-md.svg
  src/app/albalist/[userType]/page.tsx
  src/app/albalist/api/getAlbaList.ts
  src/app/albalist/components/AlbaList.tsx
  src/app/albalist/components/BlurWrapper.tsx
  src/app/albalist/components/EmptyState.tsx
  src/app/albalist/components/LoadingSkeleton.tsx
  src/app/albalist/components/SearchContainer.tsx
  src/app/albalist/layout.tsx
  src/components/button/CheckBoxButton.tsx
  src/components/button/FloatingButton.tsx
  src/components/picker/WeekPicker.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 🧑‍💻 Feat

#176 Style: Toast 기본 유형 변경 및 유형별 아이콘 수정
  public/icon/info-lg.svg
  public/icon/info-md.svg
  src/components/toast/ToastItem.tsx
  src/types/toast.ts
Labels: 🎨 Style

#177 Refactor: SolidButton 로직 수정
  src/components/button/SolidButton.tsx
Labels: ⚒️ Refactor

#167 Chore: 드롭다운 동작 시 서버전달 값을 전역상태에서 URL 파라미터로 전환
  src/app/addform/components/StepSidebar.tsx
  src/app/addform/components/WritingTag.tsx
  src/app/addform/layout.tsx
  src/app/addform/page.tsx
  src/atoms/dropdownAtomStore.ts
  src/components/dropdown/AlbaformCreateDropdown.tsx
  src/components/dropdown/AlbatalkFilterDropdown.tsx
  src/components/dropdown/ApplicationDropdown.tsx
  src/components/dropdown/OrderByDropdown.tsx
  src/components/dropdown/PublicDropdown.tsx
  src/components/dropdown/RecruitDropdown.tsx
Labels: 🔧 Chore

#178 Feat: 알바폼 만들기 페이지 사이드바 추가
  src/app/addform/components/StepButton.tsx
  src/app/addform/components/StepSidebar.tsx
  src/app/addform/page.tsx
Labels: 🧑‍💻 Feat

#179 Feat: 알바폼 만들기 페이지 임시저장 기능 및 등록 버튼 추가
  src/app/addform/components/StepButton.tsx
  src/app/addform/components/StepSidebar.tsx
  src/app/addform/page.tsx
  src/atoms/addFormAtom.ts
  src/middleware.ts
  src/types/addform.ts
Labels: 🧑‍💻 Feat

#187 Feat: 알바폼 목록 무한 스크롤 구현
  src/app/albalist/components/AlbaList.tsx
  src/app/albalist/components/EmptyState.tsx
  src/app/albalist/components/SearchContainer.tsx
  src/app/albalist/getAlbaList.ts
  src/app/albalist/hooks/useAlbaList.ts
  src/app/albalist/page.tsx
  src/components/button/CancelButton.tsx
  src/components/button/DeleteButton.tsx
  src/components/button/RoundedButton.tsx
  src/components/card/AlbarPreview.tsx
  src/components/dropdown/AlbaPreviewDropdown.tsx
  src/utils/getDday.ts
Labels: 🧑‍💻 Feat

#183 Feat: 알바폼 만들기 페이지 작성취소 버튼 추가
  src/app/addform/components/StepButton.tsx
  src/app/addform/components/Title.tsx
  src/app/addform/layout.tsx
  src/app/addform/page.tsx
  src/atoms/addFormAtom.ts
  src/components/dropdown/AlbaformCreateDropdown.tsx
Labels: 🧑‍💻 Feat

#195 Feat: StoreLocation 컴포넌트 (근무 지역, 지도 컴포넌트)
  bun.lockb
  package.json
  src/app/layout.tsx
  src/components/card/StoreLocation.tsx
  src/components/map/KakaoMap.tsx
  src/components/map/useKakaoLoader.ts
Labels: 🧑‍💻 Feat

#196 Feat: 알바폼 리스트 페이지 스켈레톤 UI 적용
  src/app/albalist/components/AlbaList.tsx
  src/app/albalist/components/AlbaListFetcher.tsx
  src/app/albalist/components/CardListSkeleton.tsx
  src/app/albalist/components/EmptyState.tsx
  src/app/albalist/components/LoadingSkeleton.tsx
  src/app/albalist/components/SearchContainer.tsx
  src/app/albalist/hooks/useAlbaList.ts
  src/app/albalist/layout.tsx
  src/app/albalist/page.tsx
Labels: 🧑‍💻 Feat

#199 Feat:알바폼 지원하기 UI 구현
  src/app/apply/[id]/components/ApplyForm.tsx
  src/app/apply/[id]/layout.tsx
  src/app/apply/[id]/page.tsx
  src/schema/apply/applySchema.ts
Labels: 🧑‍💻 Feat

#198 Feat: 알바폼만들기 페이지 1단계 form 생성, 임시저장 불러오기 추가
  src/app/addform/components/MainButton.tsx
  src/app/addform/components/StepContainer.tsx
  src/app/addform/components/StepOneContents.tsx
  src/app/addform/components/StepSidebar.tsx
  src/app/addform/components/StepThreeContents.tsx
  src/app/addform/components/StepTwoContents.tsx
  src/app/addform/components/Title.tsx
  src/app/addform/page.tsx
  src/atoms/addFormAtom.ts
  src/components/button/ImageInput.tsx
  src/components/picker/Calendar.tsx
  src/components/picker/DatepickerCalendar.tsx
  src/components/picker/RangePicker.tsx
  src/schema/addForm/addFormSchema.ts
  src/styles/globals.css
Labels: 🧑‍💻 Feat

#201 Chore: 지원하기 폼 벨리데이션 수정
  src/schema/apply/applySchema.ts
Labels: 🔧 Chore

#207 Feat: 알바 토크 글쓰기 UI 구현
  src/app/addtalk/components/AddTalkForm.tsx
  src/app/addtalk/layout.tsx
  src/app/addtalk/page.tsx
  src/app/albalist/layout.tsx
  src/components/button/ImageInput.tsx
  src/schema/addTalk/addTalkSchema.ts
Labels: 🧑‍💻 Feat

#212 Feat: AlbaPreviewCard 드롭 다운 메뉴 구현
  src/app/albalist/components/AlbaList.tsx
  src/app/albalist/components/AlbaListFetcher.tsx
  src/components/card/AlbarPreview.tsx
  src/components/dropdown/AlbaPreviewDropdown.tsx
  src/components/dropdown/DropdownMenu.tsx
  src/components/toast/ToastItem.tsx
Labels: 🧑‍💻 Feat

#217 Feat: 알바 토크 글쓰기 등록 구현
  bun.lockb
  next.config.ts
  src/app/addtalk/actions/addTalk.ts
  src/app/addtalk/actions/uploadImage.ts
  src/app/addtalk/components/AddTalkForm.tsx
  src/schema/addTalk/addTalkSchema.ts
Labels: 🧑‍💻 Feat

#249 Feat: 알바폼만들기 페이지 3단계 근무위치 모달 연결 및 값 추출
  src/app/addform/components/MainButton.tsx
  src/app/addform/components/StepButton.tsx
  src/app/addform/components/StepContainer.tsx
  src/app/addform/components/StepOneContents.tsx
  src/app/addform/components/StepThreeContents.tsx
  src/app/addform/components/StepTwoContents.tsx
  src/app/addform/components/stepThree/Location.tsx
  src/atoms/addFormAtomStore.ts
  src/components/dropdown/AlbaformCreateDropdown.tsx
  src/components/picker/LocationPicker.tsx
  src/lib/instance.ts
Labels: 🧑‍💻 Feat

#259 Feat: 내지원내역보기 -> 제출 내용 모달 ui 구현
  public/icon/write-black.svg
  src/app/albalist/hooks/useAlbaList.ts
  src/app/test/page.tsx
  src/components/input/ResumeInput.tsx
  src/components/modal/modalContent/GetMyApplicationModal.tsx
  src/components/modal/modalContent/MyApplicationModal.tsx
  src/components/modal/modalManager/ModalManager.tsx
  src/types/modal.ts
Labels: 🧑‍💻 Feat

#263 Feat: 알바 토크 상세 페이지 구현
  public/icon/modal.svg
  src/app/(auth)/signin/actions/signinActions.ts
  src/app/(auth)/signup/actions/signupActions.ts
  src/app/addtalk/actions/patchPost.ts
  src/app/addtalk/components/AddTalkForm.tsx
  src/app/addtalk/page.tsx
  src/app/albatalks/[talkId]/actions/deleteComment.ts
  src/app/albatalks/[talkId]/actions/deletePosts.ts
  src/app/albatalks/[talkId]/actions/patchComment.ts
  src/app/albatalks/[talkId]/actions/postComment.ts
  src/app/albatalks/[talkId]/actions/postLike.ts
  src/app/albatalks/[talkId]/actions/postLikeCancel.ts
  src/app/albatalks/[talkId]/components/CommentItem.tsx
  src/app/albatalks/[talkId]/components/CommentSection.tsx
  src/app/albatalks/[talkId]/components/Content.tsx
  src/app/albatalks/[talkId]/components/EmptyComments.tsx
  src/app/albatalks/[talkId]/components/Header.tsx
  src/app/albatalks/[talkId]/components/ProfileImage.tsx
  src/app/albatalks/[talkId]/getAlbaTalkDetail.ts
  src/app/albatalks/[talkId]/getComments.ts
  src/app/albatalks/[talkId]/layout.tsx
  src/app/albatalks/[talkId]/page.tsx
  src/components/button/ImageInput.tsx
  src/lib/cookie.ts
  src/lib/instance.ts
  src/schema/albaTalkComment/albaTalkCommentSchema.ts
  src/types/comment.ts
  src/utils/formatYearMonthDay.ts
Labels: 🧑‍💻 Feat

#264 Feat: "사장님 정보 수정 모달" 기능 구현
  src/app/test/page.tsx
  src/components/modal/modalActions/changeCEOInfoAction.ts
  src/components/modal/modalContent/ChangeCEOInfoModal.tsx
  src/schema/modal/changeCEOInfoSchema.ts
Labels: 🧑‍💻 Feat

#266 Feat: "비밀번호 변경" 모달 기능 구현
  src/app/test/page.tsx
  src/components/modal/modalActions/changePasswordAction.ts
  src/components/modal/modalContent/ChangePasswordModal.tsx
Labels: 🧑‍💻 Feat

#281 Feat: "지원상태 수정" 모달 기능 구현
  src/app/test/page.tsx
  src/atoms/modalAtomStore.ts
  src/components/modal/modalActions/selectProgressAction.ts
  src/components/modal/modalContent/DeleteAlbaformModal.tsx
  src/components/modal/modalContent/SelectProgressModal.tsx
  src/components/modal/modalManager/ModalManager.tsx
  src/hooks/useModal.ts
Labels: 🧑‍💻 Feat

#282 Feat: "내 지원내역 조회" 모달 기능 구현
  src/app/apply/[id]/components/ApplyForm.tsx
  src/components/modal/modalActions/getMyApplicationAction.ts
  src/components/modal/modalContent/GetMyApplicationModal.tsx
  src/schema/modal/getMyApplicationSchema.ts
Labels: 🧑‍💻 Feat

#288 Refactor: 랜딩페이지 리팩토링
  src/app/page.tsx
  src/components/button/LandingButton.tsx
Labels: ⚒️ Refactor

#289 Fix: Header컴포넌트 디버깅
  src/components/button/LoginButton.tsx
  src/components/header/Header.tsx
  src/components/header/HeaderNavigation.tsx
Labels: 🐞 Fix

#283 Feat: 알바폼 수정하기 페이지 추가
  bun.lockb
  package.json
  src/app/addform/[id]/page.tsx
  src/app/addform/actions/addFormSubmit.ts
  src/app/addform/components/LoadingSkeleton.tsx
  src/app/addform/components/MainButton.tsx
  src/app/addform/components/StepContainer.tsx
  src/app/addform/components/StepOneContents.tsx
  src/app/addform/components/StepThreeContents.tsx
  src/app/addform/components/StepTwoContents.tsx
  src/app/addform/components/Title.tsx
  src/app/addform/layout.tsx
  src/app/addform/page.tsx
  src/utils/formatAddFormDate.ts
  src/utils/formatDate.ts
  src/utils/imageFileConvert.ts
Labels: 🧑‍💻 Feat

#285 Chore: 알바폼만들기 및 수정하기 UI 수정
  src/app/addform/actions/addFormSubmit.ts
  src/app/addform/components/MainButton.tsx
  src/app/addform/components/StepOneContents.tsx
  src/app/addform/components/stepThree/IsPublicCheck.tsx
  src/app/addform/components/stepThree/Location.tsx
  src/atoms/addFormAtomStore.ts
  src/components/button/CheckBoxButton.tsx
  src/components/picker/LocationPicker.tsx
  src/components/picker/RequirementPicker.tsx
  src/hooks/useAddForm.ts
Labels: 🔧 Chore

#287 Feat: 알바 토크 상세 페이지 댓글 무한 스크롤, 로그인 안내 모달 구현
  src/app/albalist/components/AlbaList.tsx
  src/app/albatalks/[talkId]/actions/postDeleteLike.ts
  src/app/albatalks/[talkId]/actions/postLike.ts
  src/app/albatalks/[talkId]/actions/postLikeCancel.ts
  src/app/albatalks/[talkId]/components/CommentItem.tsx
  src/app/albatalks/[talkId]/components/CommentSection.tsx
  src/app/albatalks/[talkId]/components/Header.tsx
  src/app/albatalks/[talkId]/components/SkeletonCommentList.tsx
  src/app/albatalks/[talkId]/getComments.ts
  src/app/albatalks/[talkId]/page.tsx
Labels: 🧑‍💻 Feat

#297 Chore: 알바 목록 페이지 테블릿 버전 2열 배치, 폼 만들기 버튼 위치 수정
  public/icon/writing.svg
  src/app/albalist/components/AlbaList.tsx
  src/app/albalist/components/CardListSkeleton.tsx
  src/components/button/ImageInput.tsx
  src/utils/checkImageSize.ts
Labels: 🔧 Chore

#296 Fix: instance 버그 수정 및 미들웨어 최신화
  src/lib/instance.ts
  src/middleware.ts
Labels: 🐞 Fix

#298 Chore: 회원가입 및 로그인페이지 UI 수정, 가게위치 모달 연결
  src/app/(auth)/components/EazyLogin.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/signin/components/SigninContents.tsx
  src/app/(auth)/signup/[userType]/page.tsx
  src/app/(auth)/signup/components/SignupContents.tsx
  src/app/(auth)/signup/components/SignupSecondContents.tsx
  src/app/(auth)/signup/components/SignupTitle.tsx
  src/app/terms/page.tsx
Labels: 🧑‍💻 Feat, ⚒️ Refactor, 🔧 Chore

#299 Chore: 드롭다운 mb-1 삭제 후 수정필요한 드롭다운에서 해당 부분 추가
  src/components/dropdown/ApplicationDropdown.tsx
  src/components/dropdown/DropdownMenu.tsx
  src/components/dropdown/OrderByDropdown.tsx
  src/components/dropdown/PublicDropdown.tsx
  src/components/dropdown/RecruitDropdown.tsx
Labels: 🔧 Chore

#302 Chore: 알바폼 만들기 작성중 태그 활성화 여부 로직 수정
  src/app/addform/components/StepButton.tsx
  src/app/addform/components/StepContainer.tsx
  src/app/addform/components/StepOneContents.tsx
  src/app/addform/components/StepThreeContents.tsx
  src/app/addform/components/StepTwoContents.tsx
  src/app/addform/components/Title.tsx
  src/app/addtalk/components/AddTalkForm.tsx
  src/atoms/addFormAtomStore.ts
Labels: 🔧 Chore

#292 Chore: 알바토크페이지 플로팅 버튼 위치 변경
  src/app/albatalk/layout.tsx
Labels: 🔧 Chore

#290 Fix: 알바폼상세페이지 디버깅 작업(80%완료)
  src/app/alba/[formId]/components/Content.tsx
  src/app/alba/[formId]/components/DetailRequirements.tsx
  src/app/alba/[formId]/components/SimpleRequirements.tsx
  src/utils/isPast.ts
Labels: 🐞 Fix

#309 Chore: 알바폼만들기 2단계 에러위치 수정, 요청데이터 받는 코드 수정
  src/app/addform/[id]/page.tsx
  src/app/addform/actions/addFormImgUpload.ts
  src/app/addform/actions/addFormSubmit.ts
  src/app/addform/components/StepTwoContents.tsx
  src/components/picker/RequirementPicker.tsx
  src/utils/formatAddFormDate.ts
Labels: 🔧 Chore

#295 Feat: 알바폼 이어쓰기 모달 새로쓰기 버튼 추가
  src/components/modal/modalContent/PatchAlbaformModal.tsx
Labels: 🧑‍💻 Feat

#315 Chore:글쓰기 버튼 비회원 숨기기
  src/app/albatalk/components/AlbatalkList.tsx
  src/app/albatalk/layout.tsx
Labels: 🔧 Chore

#308 Feat: 마이페이지 "내가 쓴 글" 구현
  src/app/albatalk/page.tsx
  src/app/mypage/components/MyPost.tsx
  src/app/mypage/components/MyPostList.tsx
  src/app/mypage/components/NavMenu.tsx
  src/app/mypage/components/NavMenuButton.tsx
  src/app/mypage/components/TabButton.tsx
  src/app/mypage/getMyPosts.ts
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
Labels: 🧑‍💻 Feat

#310 Feat: 마이페이지 내가 쓴 댓글 구현
  src/app/mypage/components/EmptyComment.tsx
  src/app/mypage/components/MyComment.tsx
  src/app/mypage/components/MyCommentList.tsx
  src/app/mypage/components/NavMenu.tsx
  src/app/mypage/components/TabDropdown.tsx
  src/app/mypage/getMyComments.ts
  src/app/mypage/layout.tsx
  src/types/comment.ts
Labels: 🧑‍💻 Feat

#319 Refactor: 알바폼만들기 컴포넌트 리팩토링
  src/app/addform/components/LoadingSkeleton.tsx
  src/app/addform/components/MainButton.tsx
  src/app/addform/components/StepButton.tsx
  src/app/addform/components/StepContainer.tsx
  src/app/addform/components/StepOneContents.tsx
  src/app/addform/components/StepThreeContents.tsx
  src/app/addform/components/StepTwoContents.tsx
  src/app/addform/components/Title.tsx
  src/app/addform/components/stepOne/AddformImage.tsx
  src/app/addform/components/stepOne/AlbaformDescription.tsx
  src/app/addform/components/stepOne/AlbaformTitle.tsx
  src/app/addform/components/stepOne/RecruitDate.tsx
  src/app/addform/components/stepThree/WorkDay.tsx
  src/components/picker/PickableList.tsx
  src/components/picker/RequirementPicker.tsx
  src/components/picker/TimePicker.tsx
  src/hooks/useAddForm.ts
  src/hooks/useAddFormStepOne.ts
Labels: ⚒️ Refactor, 🔧 Chore

#330 Fix: 알바 토크 글쓰기 및 상세 페이지 수정
  src/app/addform/components/stepOne/AddformImage.tsx
  src/app/addtalk/actions/addTalk.ts
  src/app/addtalk/actions/patchPost.ts
  src/app/addtalk/actions/uploadImage.ts
  src/app/addtalk/components/AddTalkForm.tsx
  src/app/albatalks/[talkId]/actions/postComment.ts
  src/app/albatalks/[talkId]/getComments.ts
  src/components/button/ImageInput.tsx
Labels: 🐞 Fix

#328 Feat: not-found, error, global-error 파일 추가
  public/image/error.png
  src/app/(auth)/error.tsx
  src/app/addform/error.tsx
  src/app/addtalk/error.tsx
  src/app/alba/[formId]/error.tsx
  src/app/albalist/error.tsx
  src/app/albatalk/error.tsx
  src/app/albatalks/[talkId]/error.tsx
  src/app/apply/[id]/error.tsx
  src/app/global-error.tsx
  src/app/mypage/error.tsx
  src/app/not-found.tsx
Labels: 🧑‍💻 Feat

#325 Chore: instance 버그 수정
  src/app/addform/components/StepContainer.tsx
  src/app/api/refresh/route.ts
  src/lib/cookie.ts
  src/lib/instance.ts
Labels: 🔧 Chore

#332 Feat: 마이페이지 스크랩 구현
  src/app/mypage/components/MyComment.tsx
  src/app/mypage/components/MyCommentList.tsx
  src/app/mypage/components/MyScrap.tsx
  src/app/mypage/components/MyScrapList.tsx
  src/app/mypage/components/NavContainer.tsx
  src/app/mypage/components/TabDropdown.tsx
  src/app/mypage/getMyScraps.ts
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/components/card/CommentCard.tsx
  src/types/scrap.ts
Labels: 🧑‍💻 Feat

#345 Feat:사장님일때 스크랩 안보이기
  src/app/albatalks/[talkId]/components/EmptyComments.tsx
  src/app/mypage/actions/getRole.ts
  src/app/mypage/components/MyScrapList.tsx
  src/app/mypage/components/NavMenu.tsx
Labels: 🧑‍💻 Feat

#324 Chore: 지원하기 폼 페이지 수정사항 개선
  src/app/apply/[id]/actions/applyFormAction.ts
  src/app/apply/[id]/components/ApplyForm.tsx
  src/app/apply/[id]/components/ApplyFormButton.tsx
  src/app/apply/[id]/components/ApplyFormContainer.tsx
  src/app/apply/[id]/components/ApplyFormInputList.tsx
  src/atoms/newWrite.ts
  src/components/modal/modalContent/NewWriteformModal.tsx
  src/components/modal/modalManager/ModalManager.tsx
  src/types/apply.ts
  src/types/modal.ts
Labels: 🔧 Chore

#339 Feat: 지원현황조회 모달 -> 각 지원자 클릭시 "지원자 상세 페이지"로 이동하는 기능
  src/app/alba/[formId]/page.tsx
  src/components/ApplicantStatsList.tsx
Labels: 🧑‍💻 Feat

#343 Refactor: 알바폼 상세페이지
  src/app/alba/[formId]/fetchAlbaformData.ts
  src/app/alba/[formId]/page.tsx
  src/components/Carousel/Carousel.tsx
  src/components/header/Header.tsx
  src/components/header/Logo.tsx
Labels: ⚒️ Refactor

#337 Feat: 내 지원 상세 페이지(지원자 전용)
  src/app/alba/[formId]/fetchAlbarformDetailData.ts
  src/app/alba/[formId]/page.tsx
  src/app/alba/components/ApllicantActionButtons.tsx
  src/app/alba/components/Content.tsx
  src/app/alba/components/DetailRequirements.tsx
  src/app/alba/components/EmployerInfo.tsx
  src/app/alba/components/LinkShowAndCopy.tsx
  src/app/alba/components/MyApplication.tsx
  src/app/alba/components/NoticeApplicant.tsx
  src/app/alba/components/NoticeIsClosed.tsx
  src/app/alba/components/OwnerActionButtons.tsx
  src/app/alba/components/ScrapAndShareButton.tsx
  src/app/alba/components/SimpleRequirements.tsx
  src/app/alba/components/StoreLocation.tsx
  src/app/alba/components/Title.tsx
  src/app/myapply/[formId]/fetchApplicationData.ts
  src/app/myapply/[formId]/page.tsx
  src/components/card/ApplicationStatus.tsx
  src/components/modal/modalContent/ShareSNSModal.tsx
  src/types/alba.ts
  src/utils/getDday.ts
Labels: 🧑‍💻 Feat

#350 Chore: 액세스토큰 만료 시 새 액세스토큰 설정, 재요청 로직 수정
  src/app/api/refresh/route.ts
  src/lib/cookie.ts
  src/lib/instance.ts
  src/middleware.ts
Labels: 🔧 Chore

#351 Refactor: 지원하기 폼 인풋 컴포넌트화
  src/app/albatalk/components/AlbatalkList.tsx
  src/app/apply/[id]/components/ApplyForm.tsx
  src/app/apply/[id]/components/ApplyFormButton.tsx
  src/app/apply/[id]/components/ApplyFormInputList.tsx
  src/app/apply/[id]/components/ExperienceInput.tsx
  src/app/apply/[id]/components/IntroductionInput.tsx
  src/app/apply/[id]/components/NameInput.tsx
  src/app/apply/[id]/components/PasswordInput.tsx
  src/app/apply/[id]/components/PhoneNumberInput.tsx
  src/app/apply/[id]/components/ResumeInput.tsx
  src/styles/globals.css
Labels: ⚒️ Refactor

#356 Fix: 알바폼상세페이지에서 지원자일 때 ActionButton이 이상하게 배치되는 문제 해결
  src/app/alba/[formId]/page.tsx
  src/app/alba/components/ApllicantActionButtons.tsx
Labels: 🐞 Fix

#357 Refactor: 캐싱 전략 수정
  src/app/addform/actions/addFormSubmit.ts
  src/app/albalist/getAlbaList.ts
  src/app/albatalks/[talkId]/components/CommentItem.tsx
  src/app/albatalks/[talkId]/components/Content.tsx
  src/app/albatalks/[talkId]/getAlbaTalkDetail.ts
  src/app/albatalks/[talkId]/getComments.ts
  src/app/myalbaform/components/ListFetcher.tsx
  src/app/myalbaform/getAlbaFormList.ts
  src/app/myalbaform/getApplyList.ts
  src/app/myalbaform/page.tsx
Labels: ⚒️ Refactor

#358 Feat: 알바폼만들기페이지 모달 연결
  src/app/addform/components/StepContainer.tsx
  src/app/addform/components/StepOneContents.tsx
  src/app/addform/components/StepThreeContents.tsx
  src/hooks/useAddForm.ts
  src/hooks/useAddFormStepOne.ts
Labels: 🧑‍💻 Feat

#361 Chore: 새로운 solid 버튼 사이즈 속성에 맞게 수정
  src/app/(auth)/layout.tsx
  src/app/(auth)/signin/components/SigninContents.tsx
  src/app/(auth)/signup/components/SignupContents.tsx
  src/app/(auth)/signup/components/SignupSecondContents.tsx
  src/app/addform/components/MainButton.tsx
Labels: 🔧 Chore

#373 Feat:PostCard 썸네일 추가
  src/components/PostCardThumbnail.tsx
  src/components/card/PostCard.tsx
Labels: 🧑‍💻 Feat

#376 Fix:진행상태 변경 모달 로직 수정
  src/components/modal/modalActions/selectProgressAction.ts
  src/components/modal/modalContent/SelectProgressModal.tsx
Labels: 🐞 Fix

#365 Chore: 비회원이 접근할 수 없는 페이지 접근되는 현상 수정
  src/app/layout.tsx
  src/lib/RedirectWarning.tsx
  src/middleware.ts
Labels: 🧑‍💻 Feat, 🔧 Chore

#367 Chore: 알바폼 수정하기로 들어갔을 때 임시저장데이터 불러오지 않도록 수정
  src/app/addform/[id]/page.tsx
  src/app/addform/components/MainButton.tsx
  src/app/addform/components/StepContainer.tsx
  src/app/addform/components/StepContent.tsx
  src/app/addform/components/StepOneContents.tsx
  src/app/addform/components/StepThreeContents.tsx
  src/app/addform/components/StepTwoContents.tsx
  src/app/alba/[formId]/components/OwnerActionButtons.tsx
  src/app/alba/[formId]/fetchAlbarformDetailData.ts
Labels: 🔧 Chore

#377 Fix: 3차배포 디버깅 정준영(80% -> ResumInput만 반영하면 됨)
  src/app/addtalk/components/AddTalkForm.tsx
  src/app/alba/[formId]/components/ApllicantActionButtons.tsx
  src/app/alba/[formId]/page.tsx
  src/app/alba/components/ApllicantActionButtons.tsx
  src/app/alba/components/Title.tsx
  src/app/application/[formId]/[applicationId]/layout.tsx
  src/app/application/[formId]/[applicationId]/page.tsx
  src/app/myapply/[formId]/fetchApplicationData.ts
  src/app/myapply/[formId]/layoute.tsx
  src/app/myapply/[formId]/page.tsx
  src/app/page.tsx
  src/components/ApplicantStatsList.tsx
  src/components/card/AlbarPreview.tsx
  src/components/header/AuthPageNavigation.tsx
  src/components/header/Header.tsx
  src/components/header/HeaderNavigation.tsx
  src/components/header/Logo.tsx
  src/components/header/Sidebar.tsx
  src/styles/globals.css
Labels: 🐞 Fix

#348 Refactor: SolidButton 기본 사이즈 추가 및 로직 수정
  src/app/(auth)/layout.tsx
  src/app/(auth)/signin/components/SigninContents.tsx
  src/app/(auth)/signup/components/SignupContents.tsx
  src/app/(auth)/signup/components/SignupSecondContents.tsx
  src/app/addform/components/MainButton.tsx
  src/app/addtalk/components/AddTalkForm.tsx
  src/app/alba/components/ApllicantActionButtons.tsx
  src/app/alba/components/OwnerActionButtons.tsx
  src/app/albatalks/[talkId]/components/CommentSection.tsx
  src/app/albatalks/[talkId]/components/Header.tsx
  src/app/albatalks/[talkId]/page.tsx
  src/app/api/nonmemberinfo/route.ts
  src/app/apply/[id]/components/ApplyFormButton.tsx
  src/app/mypage/components/InfoEditContainer.tsx
  src/components/button/FloatingButton.tsx
  src/components/button/ImageInput.tsx
  src/components/button/LoginButton.tsx
  src/components/button/SolidButton.tsx
  src/components/input/SearchLocation.tsx
  src/components/modal/modalContent/ChangeCEOInfoModal.tsx
  src/components/modal/modalContent/ChangeMyInfoModal.tsx
  src/components/modal/modalContent/ChangePasswordModal.tsx
  src/components/modal/modalContent/ClosedAlbaformModal.tsx
  src/components/modal/modalContent/DeleteAlbaformModal.tsx
  src/components/modal/modalContent/GetMyApplicationModal.tsx
  src/components/modal/modalContent/NewWriteformModal.tsx
  src/components/modal/modalContent/SelectLocationModal.tsx
  src/components/modal/modalContent/SelectProgressModal.tsx
Labels: ⚒️ Refactor

#368 Chore: 알바 토크 상세 수정 및 추가
  bun.lockb
  package.json
  src/app/albatalks/[talkId]/components/Content.tsx
  src/app/albatalks/[talkId]/getAlbaTalkDetail.ts
  src/app/albatalks/[talkId]/page.tsx
  src/app/apply/[id]/components/ApplyForm.tsx
  src/app/myalbaform/components/ApplyList.tsx
  src/app/myalbaform/getApplyList.ts
  src/components/button/ViewResumeButton.tsx
  src/components/card/ApplicationInfo.tsx
Labels: 🔧 Chore

#384 Chore: 마이페이지 수정사항 개선
  src/app/(auth)/signup/actions/profileImgActions.ts
  src/app/addtalk/actions/addTalk.ts
  src/app/albatalks/[talkId]/actions/deleteComment.ts
  src/app/albatalks/[talkId]/actions/patchComment.ts
  src/app/albatalks/[talkId]/actions/postComment.ts
  src/app/mypage/components/InfoEditContainer.tsx
  src/app/mypage/getMyComments.ts
  src/app/mypage/getMyPosts.ts
  src/app/mypage/layout.tsx
  src/atoms/modalAtomStore.ts
  src/components/button/ScrapButton.tsx
  src/components/card/CommentCard.tsx
  src/components/card/PostCard.tsx
  src/components/modal/modalComponents/StoreLocationInput.tsx
  src/components/modal/modalContainer/ModalContainer.tsx
  src/components/modal/modalContent/ChangeCEOInfoModal.tsx
  src/components/modal/modalContent/ChangeMyInfoModal.tsx
  src/components/modal/modalContent/ChangePasswordModal.tsx
  src/components/modal/modalContent/NewWriteformModal.tsx
  src/components/modal/modalContent/SelectProgressModal.tsx
  src/components/modal/modalManager/ModalManager.tsx
  src/hooks/useModal.ts
  src/types/modal.ts
Labels: 🔧 Chore

#386 Chore: 메타데이터 최신화 및 배포링크로 변경
  src/app/(auth)/signin/[userType]/page.tsx
  src/app/(auth)/signup/[userType]/page.tsx
  src/app/addform/[id]/page.tsx
  src/app/addform/page.tsx
  src/app/addtalk/layout.tsx
  src/app/albalist/layout.tsx
  src/app/albatalk/layout.tsx
  src/app/albatalks/[talkId]/layout.tsx
  src/app/application/[formId]/[applicationId]/page.tsx
  src/app/apply/[id]/layout.tsx
  src/app/layout.tsx
  src/app/myalbaform/layout.tsx
  src/app/myapply/[formId]/layout.tsx
  src/app/myapply/[formId]/page.tsx
  src/app/mypage/page.tsx
  src/app/terms/page.tsx
Labels: 🔧 Chore

#388 Chore: 알바폼 수정하기 페이지 딜레이현상 완화
  src/app/addform/components/StepContainer.tsx
  src/app/addform/components/StepOneContents.tsx
  src/app/addform/components/StepTwoContents.tsx
  src/hooks/useAddFormStepOne.ts
Labels: 🔧 Chore

#389 Chore: 재요청로직만 instance로 복귀
  src/lib/instance.ts
  src/middleware.ts
Labels: 🔧 Chore

#392 Feat: 카카오 간편회원가입 요청처리 및 로그인 후 반환 값 처리
  public/image/kakao_login_large.png
  src/app/(auth)/components/EazyLogin.tsx
  src/app/(auth)/components/EazySignin.tsx
  src/app/(auth)/components/EazySignup.tsx
  src/app/(auth)/signin/[userType]/page.tsx
  src/app/(auth)/signup/[userType]/page.tsx
  src/app/(auth)/signup/actions/OAuthActions.ts
  src/app/(auth)/signup/components/SignupContents.tsx
  src/app/api/auth/kakao/route.ts
  src/app/layout.tsx
  src/app/oauth/kakao/[process]/[userType]/route.ts
  src/lib/OAuthLoginCheck.tsx
  src/lib/cookie.ts
  src/schema/signup/OAuthSchema.ts
Labels: 🧑‍💻 Feat, 🔧 Chore

#400 Chore:배포전 전체 작업 수정
  src/app/albatalk/components/PostCardSkeleton.tsx
  src/app/apply/[id]/actions/applyFormAction.ts
  src/app/apply/[id]/components/ApplyForm.tsx
  src/app/mypage/actions/getRole.ts
  src/app/mypage/components/NavContainer.tsx
  src/app/mypage/components/NavMenu.tsx
  src/app/mypage/layout.tsx
Labels: 🔧 Chore

#398 Chore: 카카오 로그인 직접 디자인 및 배치 변경
  public/icon/kakao_login_logo.png
  public/image/kakao_login_large.png
  src/app/(auth)/components/EazySignin.tsx
  src/app/(auth)/components/EazySignup.tsx
  src/app/(auth)/signin/[userType]/page.tsx
  src/app/(auth)/signin/components/SigninContents.tsx
  src/app/(auth)/signup/[userType]/page.tsx
  src/app/(auth)/signup/components/SignupContents.tsx
Labels: 🔧 Chore

#403 Chore:전체적인 이슈사항 수정
  next.config.ts
  src/app/(auth)/signin/components/SigninContents.tsx
  src/app/alba/[formId]/components/ApllicantActionButtons.tsx
  src/app/alba/[formId]/components/NoticeApplicant.tsx
  src/app/alba/[formId]/page.tsx
  src/app/alba/components/NoticeApplicant.tsx
  src/app/alba/components/NoticeIsClosed.tsx
  src/atoms/isLogged.ts
  src/components/button/LoginButton.tsx
  src/components/header/Header.tsx
  src/components/header/HeaderNavigation.tsx
  src/components/header/Sidebar.tsx
Labels: 🔧 Chore

#402 Chore: 알바 목록 공개 비공개 드롭다운 기능 삭제
  bun.lockb
  src/app/addtalk/components/AddTalkForm.tsx
  src/app/albalist/components/AlbaList.tsx
  src/app/albalist/components/AlbaListFetcher.tsx
  src/app/albalist/components/SearchContainer.tsx
  src/app/albalist/hooks/useAlbaList.ts
  src/components/card/AlbarPreview.tsx
Labels: 🔧 Chore

#412 Chore: 구글 관련 코드 삭제
  src/app/(auth)/signup/actions/OAuthActions.ts
Labels: 🔧 Chore

#410 Chore: 알바폼만들기 및 수정하기 이미지 무한루프 수정
  src/components/button/ImageInput.tsx
Labels: 🔧 Chore

#413 Docs: README.md 업데이트
  README.md
Labels: 📜 Docs
